name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  cross_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22.5' ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        run: |
          go get ./...
          sudo apt-get install golang gcc libgl1-mesa-dev xorg-dev
          sudo apt-get install gcc-multilib
          sudo apt-get install gcc-mingw-w64
      - name: Clone Cloak and copying ck-client
        run: |
          git submodule add https://github.com/cbeuw/Cloak
          git submodule init
          git submodule update
          cp -r ck-client Cloak
          cd Cloak/ck-client
          go mod tidy
          cd ../..

      - name: Build windows ck-client
        run: |
          cd Cloak/ck-client
          fyne package -os windows
          cd ../..
      - name: Windows build
        run: |
          GOOS=windows GOARCH=386 CGO_ENABLED=1 CXX=i686-w64-mingw32-g++ CC=i686-w64-mingw32-gcc go build -o dobby_client.exe ./...
      - name: Make windows zip
        run: |
          mkdir windows_client
          mv Cloak/ck-client/ck-client.exe windows_client/ck-client.exe
          mv dobby_client.exe windows_client/client-${{ github.ref_name }}.exe
          zip -r windows_client.zip windows_client
      - name: Upload Windows client
        uses: actions/upload-artifact@master
        with:
          name: windows_client.zip
          path: windows_client.zip

      - name: Build linux ck-client
        run: |
          cd Cloak/ck-client
          fyne package -os windows
          cd ../..
      - name: Linux build
        run: go build -o dobby_client -v ./...
      - name: Make linux zip
        run: |
          mkdir linux_client
          mv Cloak/ck-client/ck-client.tar.gz linux_client/ck-client
          mv dobby_client linux_client/client-${{ github.ref_name }}
          zip -r linux_client.zip linux_client
      - name: Upload Linux client
        uses: actions/upload-artifact@master
        with:
          name: linux_client.zip
          path: linux_client.zip

  macos_build:
    runs-on: macos-latest
    strategy:
      matrix:
        go-version: [ '1.22.5' ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Clone Cloak and copying ck-client
        run: |
          git submodule add https://github.com/cbeuw/Cloak
          git submodule init
          git submodule update
          cp -r ck-client Cloak
          cd Cloak/ck-client
          go mod tidy
          cd ../..

      - name: Build macos ck-client
        run: |
          cd Cloak/ck-client
          fyne package -os darwin
          cd ../..
      - name: MacOs build
        run:
          go build -o dobby_client ./...
      - name: Make macos zip
        run: |
          mkdir macos_client
          mv Cloak/ck-client/ck-client.app macos_client/ck-client
          mv dobby_client macos_client/client-${{ github.ref_name }}
          zip -r macos_client.zip macos_client
      - name: Upload MacOs client
        uses: actions/upload-artifact@master
        with:
          name: macos_client.zip
          path: macos_client.zip

  release:
    runs-on: ubuntu-latest
    needs: [cross_build, macos_build]
    permissions: write-all

    steps:
      - uses: actions/checkout@v2

      - name: Make release dir
        run: mkdir release

      - name: Download linux client
        uses: actions/download-artifact@master
        with:
          name: linux_client.zip
          path: release
      - name: Download windows client
        uses: actions/download-artifact@master
        with:
          name: windows_client.zip
          path: release
      - name: Download macos client
        uses: actions/download-artifact@master
        with:
          name: macos_client.zip
          path: release
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
